
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "V_RATE_MST" ("RATE_PK_ID", "VENDOR_ID", "RATE_REF_NO", "RATE_FROM_COUN", "FROM_COUN_NAME", "RATE_FROM_PORT", "FROM_PORT_NAME", "FROM_PORT_CODE", "RATE_TO_COUN", "TO_COUN_NAME", "RATE_TO_PORT", "TO_PORT_NAME", "TO_PORT_CODE", "FCL_LCL_FLAG", "FCL_CONTAINER_TYPE", "CONT_TYPE_NAME", "RATE", "FCL_RATE", "LCL_RATE", "TRANSIT_TIME", "VALID_FROM", "VALID_TO", "CUSER", "CDATE", "UUSER", "UDATE") AS 
  SELECT R.PK_ID AS RATE_PK_ID,
    VENDOR_ID,
    RATE_REF_NO,
    RATE_FROM_COUN,
    FROM_COUN.COUN_NAME AS FROM_COUN_NAME,
    RATE_FROM_PORT,
    INITCAP(FROM_PORT.PORT_NAME) AS FROM_PORT_NAME,
    FROM_PORT.PORT_CODE AS FROM_PORT_CODE,
    RATE_TO_COUN,
    TO_COUN.COUN_NAME AS TO_COUN_NAME,
    RATE_TO_PORT,
    INITCAP(TO_PORT.PORT_NAME) AS TO_PORT_NAME,
    TO_PORT.PORT_CODE AS TO_PORT_CODE,
    FCL_LCL_FLAG,
    FCL_CONTAINER_TYPE,
    CASE WHEN FCL_LCL_FLAG = 'FCL' THEN CONT.CONT_TYPE ELSE 'Not Applicable' END AS CONT_TYPE_NAME,
    CASE WHEN FCL_LCL_FLAG = 'FCL' THEN FCL_RATE ELSE LCL_RATE END AS RATE,
    FCL_RATE,
    LCL_RATE,
    TRANSIT_TIME,
    VALID_FROM,
    VALID_TO,
    CUSER,
    CDATE,
    UUSER,
    UDATE FROM RATE_MST R
    JOIN COUN_MST FROM_COUN ON R.RATE_FROM_COUN = FROM_COUN.PK_ID
    JOIN COUN_MST TO_COUN ON R.RATE_TO_COUN = TO_COUN.PK_ID
    JOIN PORT_DET FROM_PORT ON R.RATE_FROM_PORT = FROM_PORT.PK_ID
    JOIN PORT_DET TO_PORT ON R.RATE_TO_PORT = TO_PORT.PK_ID
    LEFT JOIN CONTAINER_MST CONT ON R.FCL_CONTAINER_TYPE = CONT.PK_ID;